# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoppingList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShoppingList
pod 'Popover'

pod 'Auth0'
pod 'SwiftKeychainWrapper'
pod 'Alamofire'
pod 'SimpleKeychain'
pod 'Kingfisher'
pod 'PusherSwift'
pod 'PushNotifications'
pod 'TUSafariActivity', '~> 1.0'

pod 'Firebase/Core'
pod 'Firebase/Storage'


end
